// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SaveUp.Data;

#nullable disable

namespace SaveUp.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20260212201157_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SaveUp.Models.BodyGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubGroup")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BodyGroups");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Chest"
                        },
                        new
                        {
                            Id = new Guid("22222222-1111-1111-1111-111111111111"),
                            Name = "Back"
                        },
                        new
                        {
                            Id = new Guid("33333333-1111-1111-1111-111111111111"),
                            Name = "Legs"
                        },
                        new
                        {
                            Id = new Guid("44444444-1111-1111-1111-111111111111"),
                            Name = "Shoulders"
                        });
                });

            modelBuilder.Entity("SaveUp.Models.Exercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BodyGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BodyGroupId");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaa1-1111-1111-1111-111111111111"),
                            BodyGroupId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Description = "Compound chest pressing movement.",
                            Title = "Barbell Bench Press"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaa2-1111-1111-1111-111111111111"),
                            BodyGroupId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Description = "Upper chest focused pressing movement.",
                            Title = "Incline Dumbbell Press"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaa3-1111-1111-1111-111111111111"),
                            BodyGroupId = new Guid("22222222-1111-1111-1111-111111111111"),
                            Description = "Bodyweight vertical pulling movement.",
                            Title = "Pull Ups"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaa4-1111-1111-1111-111111111111"),
                            BodyGroupId = new Guid("33333333-1111-1111-1111-111111111111"),
                            Description = "Compound lower body movement.",
                            Title = "Barbell Squats"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaa5-1111-1111-1111-111111111111"),
                            BodyGroupId = new Guid("44444444-1111-1111-1111-111111111111"),
                            Description = "Overhead pressing for shoulders.",
                            Title = "Shoulder Press"
                        });
                });

            modelBuilder.Entity("SaveUp.Models.Workout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Workouts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("90000000-0000-0000-0000-000000000001"),
                            Date = new DateTime(2026, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Push Day",
                            UserId = "user@test.com"
                        });
                });

            modelBuilder.Entity("SaveUp.Models.WorkoutExercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<Guid>("WorkoutId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("WorkoutId");

                    b.ToTable("WorkoutExercises");

                    b.HasData(
                        new
                        {
                            Id = new Guid("90000000-0000-0000-0000-000000000002"),
                            ExerciseId = new Guid("aaaaaaa1-1111-1111-1111-111111111111"),
                            Order = 1,
                            WorkoutId = new Guid("90000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("90000000-0000-0000-0000-000000000003"),
                            ExerciseId = new Guid("aaaaaaa5-1111-1111-1111-111111111111"),
                            Order = 2,
                            WorkoutId = new Guid("90000000-0000-0000-0000-000000000001")
                        });
                });

            modelBuilder.Entity("SaveUp.Models.WorkoutSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("int");

                    b.Property<int>("Reps")
                        .HasColumnType("int");

                    b.Property<int>("SetNumber")
                        .HasColumnType("int");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("WorkoutExerciseId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutExerciseId");

                    b.ToTable("WorkoutSets");

                    b.HasData(
                        new
                        {
                            Id = new Guid("90000000-0000-0000-0000-000000000004"),
                            Reps = 10,
                            SetNumber = 1,
                            Weight = 80m,
                            WorkoutExerciseId = new Guid("90000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("90000000-0000-0000-0000-000000000005"),
                            Reps = 8,
                            SetNumber = 2,
                            Weight = 85m,
                            WorkoutExerciseId = new Guid("90000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("90000000-0000-0000-0000-000000000006"),
                            Reps = 12,
                            SetNumber = 1,
                            Weight = 25m,
                            WorkoutExerciseId = new Guid("90000000-0000-0000-0000-000000000003")
                        });
                });

            modelBuilder.Entity("SaveUp.Models.Exercise", b =>
                {
                    b.HasOne("SaveUp.Models.BodyGroup", "BodyGroup")
                        .WithMany("Exercises")
                        .HasForeignKey("BodyGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BodyGroup");
                });

            modelBuilder.Entity("SaveUp.Models.WorkoutExercise", b =>
                {
                    b.HasOne("SaveUp.Models.Exercise", "Exercise")
                        .WithMany("WorkoutExercises")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SaveUp.Models.Workout", "Workout")
                        .WithMany("WorkoutExercises")
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("SaveUp.Models.WorkoutSet", b =>
                {
                    b.HasOne("SaveUp.Models.WorkoutExercise", "WorkoutExercise")
                        .WithMany("Sets")
                        .HasForeignKey("WorkoutExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkoutExercise");
                });

            modelBuilder.Entity("SaveUp.Models.BodyGroup", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("SaveUp.Models.Exercise", b =>
                {
                    b.Navigation("WorkoutExercises");
                });

            modelBuilder.Entity("SaveUp.Models.Workout", b =>
                {
                    b.Navigation("WorkoutExercises");
                });

            modelBuilder.Entity("SaveUp.Models.WorkoutExercise", b =>
                {
                    b.Navigation("Sets");
                });
#pragma warning restore 612, 618
        }
    }
}
